# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coster.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63oster.proto\"&\n\x08\x42oarding\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\"\'\n\tDeparture\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\"(\n\nDisembark_\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\"*\n\x0cSubscription\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03_id\x18\x02 \x01(\t\".\n\x0cNotification\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x03\x41\x63k\x12\r\n\x05value\x18\x01 \x01(\x08\x32=\n\x05Wagon\x12\x18\n\x05\x42oard\x12\t.Boarding\x1a\x04.Ack\x12\x1a\n\x06\x44\x65part\x12\n.Departure\x1a\x04.Ack2\x94\x01\n\rRollerCoaster\x12 \n\tSubscribe\x12\r.Subscription\x1a\x04.Ack\x12\"\n\x0bUnsubscribe\x12\r.Subscription\x1a\x04.Ack\x12\x1d\n\x06Notify\x12\r.Notification\x1a\x04.Ack\x12\x1e\n\tDisembark\x12\x0b.Disembark_\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOARDING']._serialized_start=16
  _globals['_BOARDING']._serialized_end=54
  _globals['_DEPARTURE']._serialized_start=56
  _globals['_DEPARTURE']._serialized_end=95
  _globals['_DISEMBARK_']._serialized_start=97
  _globals['_DISEMBARK_']._serialized_end=137
  _globals['_SUBSCRIPTION']._serialized_start=139
  _globals['_SUBSCRIPTION']._serialized_end=181
  _globals['_NOTIFICATION']._serialized_start=183
  _globals['_NOTIFICATION']._serialized_end=229
  _globals['_ACK']._serialized_start=231
  _globals['_ACK']._serialized_end=251
  _globals['_WAGON']._serialized_start=253
  _globals['_WAGON']._serialized_end=314
  _globals['_ROLLERCOASTER']._serialized_start=317
  _globals['_ROLLERCOASTER']._serialized_end=465
# @@protoc_insertion_point(module_scope)
